name: 'Composite Container'
description: 'Test container action in composite'
inputs:
  username:
    description: 'Username'
    required: true
  token:
    description: 'Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: MegaLinter
      uses: oxsecurity/megalinter/flavors/javascript@v8.5.0
